#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# gh resolves the repo from the remote URL; ours uses an SSH host alias it cannot map, so name it.
export GH_REPO="JakeJamesDev/formamorph"
PACKAGE_NAME="ai.formamorph.app"

# Re-runs remember the folder and alias here. The password is never written anywhere.
ENV_FILE="$HOME/.formamorph-android-signing.env"

# Windows-native keytool cannot open a POSIX path; hand it a Windows one where cygpath exists.
winpath() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

banner "Formamorph Android signing and developer verification"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Play Console — developer verification"
say "Google requires a verified developer for sideloaded apps on certified devices."
say "Global enforcement starts in 2027; four countries start 2026-09-30."
say "Verifying through the Play Console covers apps on and off Play."
open_url "https://play.google.com/console/signup"
step "Sign in with the Google account that should own Formamorph."
step "Create a developer account if none exists. Pick Personal or Organization."
step "Complete identity verification: government ID, and a verified website for an organization."
note "Verification can take days. The wizard does not wait for it; continue with the key now."
pause "Press Enter once the account exists and verification is submitted or done."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Release keystore"
say "Android accepts an update only when it is signed with the same key as the installed app."
say "This key is permanent. Losing it orphans every install."
ask SIGNING_DIR "Folder for the keystore, outside the repo [$HOME/formamorph-android-signing]:"
SIGNING_DIR="${SIGNING_DIR:-$HOME/formamorph-android-signing}"
ask KEY_ALIAS "Key alias [formamorph]:"
KEY_ALIAS="${KEY_ALIAS:-formamorph}"
write_env SIGNING_DIR "$SIGNING_DIR"
write_env KEY_ALIAS "$KEY_ALIAS"
mkdir -p "$SIGNING_DIR"
KEYSTORE="$SIGNING_DIR/formamorph-release.p12"

if [[ -f "$KEYSTORE" ]]; then
  warn "A keystore already exists at $KEYSTORE."
  if confirm "Overwrite it? Every existing install would stop updating."; then
    rm -f "$KEYSTORE"
  else
    say "Keeping the existing keystore."
  fi
fi

if [[ ! -f "$KEYSTORE" ]]; then
  while :; do
    ask_secret KS_PW "Choose the keystore password:"
    ask_secret KS_PW2 "Type it again:"
    [[ -n "$KS_PW" && "$KS_PW" == "$KS_PW2" ]] && break
    warn "Passwords are empty or do not match. Try again."
  done
  export KS_PW
  say "Generating a 4096-bit RSA key valid for 10,000 days..."
  keytool -genkeypair -v -storetype PKCS12 \
    -keystore "$(winpath "$KEYSTORE")" -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 4096 -validity 10000 \
    -storepass:env KS_PW -keypass:env KS_PW \
    -dname "CN=Formamorph, O=Formamorph, C=US"
  say "Keystore written to $KEYSTORE"
else
  ask_secret KS_PW "Password of the existing keystore:"
  export KS_PW
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Back up the key"
say "Certificate fingerprint (Google asks for this when registering the app):"
keytool -list -v -keystore "$(winpath "$KEYSTORE")" -storepass:env KS_PW 2>/dev/null | grep -E 'SHA(1|256):' | sed 's/^/    /'
printf '\n'
step "Add an entry to the password manager with the keystore file attached."
step "Store the alias ($KEY_ALIAS) and the password in the same entry."
step "Keep a second copy of the file somewhere that is not this machine and not GitHub."
pause "Press Enter once the file, alias, and password are backed up."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions secrets"
say "The release workflow signs the APK from these four secrets."
B64=$(base64 -w0 "$KEYSTORE")
set_secret ANDROID_KEYSTORE_BASE64 "$B64"
set_secret ANDROID_KEYSTORE_PASSWORD "$KS_PW"
set_secret ANDROID_KEY_ALIAS "$KEY_ALIAS"
set_secret ANDROID_KEY_PASSWORD "$KS_PW"
note "PKCS12 uses one password for the store and the key, so the two password secrets match."
unset B64 KS_PW KS_PW2

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Register the app with Google"
say "Google links the package name and signing key to the verified account by taking a signed APK."
say "That APK comes from the first CI release build. Skip this stage until one exists."
if confirm "Do you have a signed Formamorph APK from CI?"; then
  open_url "https://play.google.com/console"
  step "Open the section for apps distributed outside Google Play."
  note "The exact menu name is not verified; look for outside-Play or sideloaded app registration."
  step "Add package name $PACKAGE_NAME."
  step "Upload the signed APK when asked, or paste the fingerprint from stage 3."
  pause "Press Enter once the app shows as registered."
else
  say "Re-run this wizard after the first tagged release. Stages 1 to 4 keep their values."
fi

finish
