#!/usr/bin/env bash
#
# Formamorph - one-time Cloudflare setup for the formamorph.ai/play deploy.
#
# Walks a human through the dashboard-only half of the Cloudflare Pages pipeline:
# the API token, the Pages project, the .ai custom domain, the .com redirect, and
# the two GitHub secrets plus the variable that arms the release workflow's live
# checks. Every stage verifies itself before it advances, and re-running is safe -
# a stage that is already done reports so and skips its manual instructions.
#
# Run it from the repo root:  bash scripts/cloudflare-setup.sh
#
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

PROJECT="formamorph"          # must match --project-name in .github/workflows/release.yml
BRANCH="main"                 # must match --branch in the same command
APEX="formamorph.ai"          # the Pages custom domain
ALIAS="formamorph.com"        # redirects to APEX
CF_API="https://api.cloudflare.com/client/v4"

# Nothing here is persisted. The Cloudflare API token is shown once by the
# dashboard and lives only in this process. write_env is never called, and
# _existing's -f test is false for a character device, so no .env is consulted.
ENV_FILE="/dev/null"

# ── Wizard-local helpers ──────────────────────────────────────────────────

# browse URL - open_url's Windows branch (explorer.exe) exits 1 even on success,
# which would warn on every stage. Use `start` there; delegate everywhere else.
browse() {
  case "${OSTYPE:-}" in
    msys*|cygwin*)
      printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$1"
      cmd //c start "" "$1" >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $1"
      ;;
    *) open_url "$1" ;;
  esac
}

# copyable "..." - a value the human pastes into a dashboard field.
copyable() { printf '      %s%s%s\n' "$BOLD" "$1" "$RESET"; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# cf_api METHOD PATH [JSON] - call the Cloudflare API. Sets CF_CODE and CF_BODY.
CF_CODE=""; CF_BODY=""
cf_api() {
  local method="$1" path="$2" data="${3:-}" out
  local args=(-sS --max-time 30 -X "$method"
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN:-}"
    -H "Content-Type: application/json"
    -w '\n%{http_code}')
  [ -n "$data" ] && args+=(--data "$data")
  out=$(curl "${args[@]}" "${CF_API}${path}" 2>/dev/null) || out=$'\n000'
  CF_CODE="${out##*$'\n'}"
  CF_BODY="${out%$'\n'*}"
}

# cf_field dot.path - read a value out of the last CF_BODY. Empty if absent.
cf_field() {
  _J="$CF_BODY" _P="$1" node -e '
    let v; try { v = JSON.parse(process.env._J) } catch { process.exit(0) }
    for (const k of process.env._P.split(".")) { if (v == null) break; v = v[k] }
    if (v !== undefined && v !== null) process.stdout.write(String(v))
  ' 2>/dev/null || true
}

# cf_domain_status NAME - status of one custom domain in the last CF_BODY.
cf_domain_status() {
  _J="$CF_BODY" _N="$1" node -e '
    let d; try { d = JSON.parse(process.env._J) } catch { process.exit(0) }
    const hit = (d.result || []).find(x => x && x.name === process.env._N)
    if (hit) process.stdout.write(String(hit.status || ""))
  ' 2>/dev/null || true
}

# doh_a NAME - A-record addresses via Cloudflare DNS-over-HTTPS, one per line.
# A NODATA answer is Status 0 with no Answer array, so both must be checked.
doh_a() {
  local body
  body=$(curl -sS --max-time 20 -H 'accept: application/dns-json' \
    "https://cloudflare-dns.com/dns-query?name=$1&type=A" 2>/dev/null) || body=""
  _J="$body" node -e '
    let d; try { d = JSON.parse(process.env._J) } catch { process.exit(0) }
    if (d.Status !== 0 || !Array.isArray(d.Answer)) process.exit(0)
    for (const a of d.Answer) if (a.type === 1) console.log(a.data)
  ' 2>/dev/null || true
}

# is_cf_ip IP - true when IP falls inside Cloudflare's published IPv4 ranges.
# Returns 2 when the range list could not be fetched, so callers can degrade.
CF_RANGES=""
is_cf_ip() {
  if [ -z "$CF_RANGES" ]; then
    CF_RANGES=$(curl -sS --max-time 20 https://www.cloudflare.com/ips-v4 2>/dev/null) || CF_RANGES=""
  fi
  [ -n "$CF_RANGES" ] || return 2
  _IP="$1" _R="$CF_RANGES" node -e '
    const n = s => s.split(".").reduce((a, o) => (((a << 8) >>> 0) + (+o)) >>> 0, 0)
    const ip = n(process.env._IP)
    for (const cidr of process.env._R.split(/\s+/).filter(Boolean)) {
      const [base, bits] = cidr.split("/")
      const mask = +bits === 0 ? 0 : (0xFFFFFFFF << (32 - +bits)) >>> 0
      if (((ip & mask) >>> 0) === ((n(base) & mask) >>> 0)) process.exit(0)
    }
    process.exit(1)
  ' 2>/dev/null
}

# probe URL - "<status> <resolved Location>" for one request, no redirect following.
# curl writes the -w line even when the request fails, so an unreachable host
# already yields "000 ". Only a curl that never runs needs the fallback.
probe() {
  local out
  out=$(curl -sS --max-time 20 -o /dev/null -w '%{http_code} %{redirect_url}' "$1" 2>/dev/null) || true
  [ -n "$out" ] || out="000 "
  printf '%s' "$out"
}

# expect LABEL EXPECTED ACTUAL - one assertion; sets CHECK_FAIL on mismatch.
CHECK_FAIL=0
expect() {
  if [ "$2" = "$3" ]; then ok "$1 -> $3"
  else bad "$1 - expected '$2', got '$3'"; CHECK_FAIL=1; fi
}

# gh_put_secret / gh_put_var NAME VALUE - try gh, report whether it landed. The
# library's set_secret records a skip before the manual fallback can run, which
# would make a finished run print an unfinished summary.
gh_put_secret() {
  command -v gh >/dev/null 2>&1 || return 1
  printf '%s' "$2" | gh secret set "$1" >/dev/null 2>&1 || return 1
  WRITTEN_SECRET+=("$1")
  ok "gh set the $1 secret"
}
gh_put_var() {
  command -v gh >/dev/null 2>&1 || return 1
  gh variable set "$1" --body "$2" >/dev/null 2>&1 || return 1
  ok "gh set the $1 variable"
}

# verify LABEL CHECKER - run CHECKER until it passes, or the human skips/aborts.
# Always returns 0 so `set -e` never kills the wizard on a skipped check.
verify() {
  local label="$1" fn="$2" reply=""
  while true; do
    if "$fn"; then
      printf '  %s✓ verified:%s %s\n' "$GREEN" "$RESET" "$label"
      return 0
    fi
    printf '\n  %s? [r]etry  [s]kip this check  [a]bort the wizard%s ' "$YELLOW" "$RESET"
    # An empty answer retries, so a closed stdin (Ctrl-D) would spin forever.
    if ! read -r reply; then printf '\n'; warn "input closed - stopping"; exit 1; fi
    case "$reply" in
      s|S) SKIPPED+=("$label - verify by hand"); warn "skipped without verifying"; return 0 ;;
      a|A) printf '\n'; exit 1 ;;
      *) printf '\n' ;;
    esac
  done
}

# ── Verification checks ───────────────────────────────────────────────────
# One function per stage. Each prints its own evidence, returns 0 only when the
# real world matches the contract, and is safe to call before the stage runs -
# that is how a re-run knows a stage is already done.

check_token() {
  CHECK_FAIL=0
  cf_api GET "/user/tokens/verify"
  expect "token verify HTTP" "200" "$CF_CODE"
  expect "token status" "active" "$(cf_field result.status)"
  # A wrong account ID, or a token without Pages Edit, fails here rather than
  # three stages later with a confusing 404.
  cf_api GET "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects"
  expect "Pages access for account ${CLOUDFLARE_ACCOUNT_ID}" "200" "$CF_CODE"
  [ "$CHECK_FAIL" -eq 0 ]
}

check_project() {
  CHECK_FAIL=0
  cf_api GET "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT}"
  expect "project lookup HTTP" "200" "$CF_CODE"
  [ "$CHECK_FAIL" -eq 0 ] || return 1
  expect "project name" "$PROJECT" "$(cf_field result.name)"
  # Top-level field. A Git-connected project also carries one under
  # result.source.config, which is not the value the deploy honors.
  expect "production branch" "$BRANCH" "$(cf_field result.production_branch)"
  [ "$CHECK_FAIL" -eq 0 ]
}

# Writes the production branch back to the value check_project just confirmed it
# already has. Reading a project succeeds with a Pages Read token, which would
# then 403 at deploy time, so only a write proves the Edit scope the workflow
# needs. Run it after check_project, never alone: the PATCH is a no-op only while
# the branch already matches.
check_pages_write() {
  CHECK_FAIL=0
  cf_api PATCH "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT}" \
    "{\"production_branch\":\"${BRANCH}\"}"
  expect "token can write the project (Pages Edit)" "200" "$CF_CODE"
  [ "$CHECK_FAIL" -eq 0 ]
}

check_project_ready() { check_project && check_pages_write; }

check_domain() {
  CHECK_FAIL=0
  cf_api GET "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT}/domains"
  expect "domain list HTTP" "200" "$CF_CODE"
  [ "$CHECK_FAIL" -eq 0 ] || return 1
  local status
  status=$(cf_domain_status "$APEX")
  [ -n "$status" ] || status="(not attached)"
  # Cloudflare passes through initializing and pending before it reaches active.
  if [ "$status" = "active" ]; then ok "${APEX} -> active"; return 0; fi
  bad "${APEX} - expected 'active', got '${status}'"
  return 1
}

# Five minutes of polling, then back to verify() for another round. Cloudflare's
# own escalation threshold is fifteen minutes.
poll_domain() {
  local i
  for i in $(seq 1 15); do
    if check_domain; then return 0; fi
    [ "$i" -eq 15 ] && return 1
    note "still waiting (${i}/15)"
    sleep 20
  done
  return 1
}

check_alias_dns() {
  CHECK_FAIL=0
  local name ips ip found rc
  for name in "$ALIAS" "www.${ALIAS}"; do
    ips=$(doh_a "$name")
    if [ -z "$ips" ]; then bad "${name} - no A record"; CHECK_FAIL=1; continue; fi
    found=0
    for ip in $ips; do
      if [ "$ip" = "192.0.2.1" ]; then
        bad "${name} -> 192.0.2.1 (record is not proxied; turn the cloud orange)"
        CHECK_FAIL=1; found=1; break
      fi
      is_cf_ip "$ip" && rc=0 || rc=$?
      if [ "$rc" -eq 0 ]; then
        ok "${name} -> ${ip} (Cloudflare edge)"; found=1; break
      elif [ "$rc" -eq 2 ]; then
        # Passing an unverified address here would be the one "assume ok".
        bad "cannot reach Cloudflare's published IP list - retry in a moment"
        CHECK_FAIL=1; found=1; break
      fi
    done
    if [ "$found" -eq 0 ]; then
      bad "${name} -> $(printf '%s' "$ips" | tr '\n' ' ')(not a Cloudflare address)"
      CHECK_FAIL=1
    fi
  done
  [ "$CHECK_FAIL" -eq 0 ]
}

check_redirect() {
  CHECK_FAIL=0
  # The first probe is the exact assertion the release workflow makes.
  expect "https://${ALIAS}/play/" \
    "301 https://${APEX}/play/" "$(probe "https://${ALIAS}/play/")"
  # The second proves the www record, the path, and the query string all survive.
  expect "https://www.${ALIAS}/a/b?x=1&y=2" \
    "301 https://${APEX}/a/b?x=1&y=2" "$(probe "https://www.${ALIAS}/a/b?x=1&y=2")"
  [ "$CHECK_FAIL" -eq 0 ]
}

check_secrets() {
  CHECK_FAIL=0
  local out name
  out=$(gh secret list 2>/dev/null) || { bad "gh could not list secrets"; return 1; }
  for name in CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID; do
    if printf '%s\n' "$out" | grep -q "^${name}[[:space:]]"; then ok "${name} is set"
    else bad "${name} is missing"; CHECK_FAIL=1; fi
  done
  [ "$CHECK_FAIL" -eq 0 ]
}

check_var() {
  CHECK_FAIL=0
  local out
  out=$(gh variable list 2>/dev/null) || { bad "gh could not list variables"; return 1; }
  if printf '%s\n' "$out" | grep -qE "^CLOUDFLARE_CHECKS[[:space:]]+true([[:space:]]|$)"; then
    ok "CLOUDFLARE_CHECKS = true"
  else
    bad "CLOUDFLARE_CHECKS is not set to 'true'"; CHECK_FAIL=1
  fi
  [ "$CHECK_FAIL" -eq 0 ]
}

# gh_stage LABEL READ_PROBE CHECKER INSTRUCTIONS URL - stages 6 and 7 both write
# through gh, then confirm. gh reads Actions settings only when its token carries
# that scope, so a missing scope becomes a human eyeball rather than a retry loop
# that can never turn green.
gh_stage() {
  local label="$1" read_probe="$2" checker="$3" instructions="$4" url="$5"
  if command -v gh >/dev/null 2>&1 && "$read_probe"; then
    if "$checker"; then note "${label} confirmed on ${REPO_SLUG}."; return 0; fi
    "$instructions"
    browse "$url"
    pause "Press Enter once it is saved."
    verify "${label} on ${REPO_SLUG}" "$checker"
    return 0
  fi
  warn "gh cannot read this repository's Actions settings, so this stage ends"
  warn "with your own check in the GitHub UI."
  "$instructions"
  browse "$url"
  if confirm "Does that page show what it should?"; then
    ok "confirmed by hand"
  else
    SKIPPED+=("${label} on ${REPO_SLUG}")
  fi
}

# ── Preflight ─────────────────────────────────────────────────────────────

missing=()
for tool in curl node; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if (( ${#missing[@]} )); then
  printf '\n%s  Missing required tool(s): %s%s\n\n' "$RED" "${missing[*]}" "$RESET"
  printf '  Every stage checks itself with curl, and node parses the answers.\n\n'
  exit 1
fi
# Each of these serves one stage. Say so now rather than at the stage that needs it.
command -v npx >/dev/null 2>&1 || warn "no npx: stage 2 cannot create the Pages project"
command -v git >/dev/null 2>&1 || warn "no git: stage 6 will ask for the repository by hand"
command -v gh  >/dev/null 2>&1 || warn "no gh: stages 6 and 7 are done entirely in the GitHub UI"

banner "Formamorph - Cloudflare setup for formamorph.ai"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Cloudflare account ID and API token"
say "Every later stage verifies itself through the Cloudflare API, so the token"
say "comes first. It is never written to disk - only this process holds it."
printf '\n'
step "Account ID: on the Workers & Pages page, open the Account Details panel and"
step "use the copy button next to Account ID."
browse "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
printf '\n'
step "Token: Create Token -> Custom token -> Get started."
step "Name it 'Formamorph Pages Deploy'."
step "Under Permissions pick:  Account  |  Cloudflare Pages  |  Edit"
step "Continue to summary -> Create Token, then copy it. Cloudflare shows it once."
browse "https://dash.cloudflare.com/profile/api-tokens"
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (hidden):"
export CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN
printf '\n'

# verify() re-runs its checker against the same globals, so retrying check_token
# alone could never change the answer. Re-ask first, then check.
reask_token() {
  ask CLOUDFLARE_ACCOUNT_ID "Account ID:"
  ask_secret CLOUDFLARE_API_TOKEN "API token (hidden):"
  export CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN
  check_token
}
if ! check_token; then
  warn "Re-enter the values and try again."
  verify "token and account ID reach the Pages API" reask_token
fi

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Pages project 'formamorph' on branch 'main'"
say "The release workflow runs:"
say "  pages deploy out --project-name=${PROJECT} --branch=${BRANCH}"
say "Both values must match the project, or the deploy files a preview build that"
say "never reaches the custom domain."
printf '\n'

if check_project_ready; then
  note "Already created - nothing to do."
else
  cf_api GET "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT}"
  if [ "$CF_CODE" = "200" ]; then
    # The project exists on the wrong production branch. The dashboard shows no
    # control for this on a Direct Upload project, so patch it over the API.
    say "The project exists. Its production branch is:"
    copyable "$(cf_field result.production_branch)"
    if confirm "Set it to '${BRANCH}' now?"; then
      cf_api PATCH "/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT}" \
        "{\"production_branch\":\"${BRANCH}\"}"
      expect "patch HTTP" "200" "$CF_CODE"
    fi
  else
    say "The dashboard cannot do this step. Its create flow demands files up front"
    say "and hides production-branch controls on Direct Upload projects. Wrangler"
    say "creates an empty project and takes the branch as a flag."
    printf '\n'
    warn "Direct Upload is permanent: such a project can never become Git-connected."
    if confirm "Create Pages project '${PROJECT}' with production branch '${BRANCH}'?"; then
      if npx --yes wrangler@4 pages project create "$PROJECT" --production-branch "$BRANCH"; then
        ok "wrangler reported success"
      else
        warn "wrangler failed - read its output above."
      fi
    fi
  fi
  verify "Pages project '${PROJECT}' exists on branch '${BRANCH}'" check_project_ready
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Custom domain formamorph.ai"

if check_domain; then
  note "Already attached and active - nothing to do."
else
  say "Cloudflare writes the DNS record itself. Do not hand-create one first: an"
  say "apex CNAME added outside this flow serves a 522."
  printf '\n'
  step "Open the project, then its Custom domains tab."
  step "Set up a domain -> enter the domain -> Continue -> Activate domain."
  copyable "${APEX}"
  browse "https://dash.cloudflare.com/?to=/${CLOUDFLARE_ACCOUNT_ID}/pages/view/${PROJECT}"
  pause "Press Enter once you have submitted it; validation runs in the background."
  printf '\n'
  say "Polling for five minutes. Cloudflare validates over HTTP and usually"
  say "settles within a couple; past fifteen, something is wrong."
  verify "${APEX} is an active custom domain on '${PROJECT}'" poll_domain
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Placeholder DNS records on formamorph.com"
say "${ALIAS} needs no origin. It only has to reach Cloudflare's edge, so a"
say "rule can answer. A proxied record at the reserved documentation address"
say "does that: the address routes nowhere, and the proxy answers first."
printf '\n'

if check_alias_dns; then
  note "Already wired - nothing to do."
else
  step "Add two records on ${ALIAS}, both proxied (orange cloud):"
  copyable "A    @      192.0.2.1    Proxied"
  copyable "A    www    192.0.2.1    Proxied"
  browse "https://dash.cloudflare.com/?to=/${CLOUDFLARE_ACCOUNT_ID}/${ALIAS}/dns/records"
  pause "Press Enter once both records are saved."
  note "A proxied record answers with a Cloudflare address, never 192.0.2.1, so that"
  note "is what this checks. Proxied TTL is pinned at 300s, so a retry may be needed."
  verify "${ALIAS} and www.${ALIAS} resolve to Cloudflare's edge" check_alias_dns
fi

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Redirect rule: formamorph.com -> formamorph.ai"

if check_redirect; then
  note "Already redirecting - nothing to do."
else
  step "On the ${ALIAS} zone: Create rule -> Redirect Rule."
  step "Name it, then choose 'All incoming requests'."
  step "Under Then, set Type to Dynamic and paste this expression:"
  copyable 'concat("https://formamorph.ai", http.request.uri.path)'
  step "Status code 301. Turn ON 'Preserve query string'. Then Deploy."
  note "Type must be Dynamic. A Static target emits a literal Location and drops"
  note "the path, so /play/ would land on the bare root."
  browse "https://dash.cloudflare.com/?to=/${CLOUDFLARE_ACCOUNT_ID}/${ALIAS}/rules/overview"
  pause "Press Enter once the rule is deployed."
  verify "${ALIAS} redirects to ${APEX} with path and query intact" check_redirect
fi

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "GitHub repository secrets"

REPO_SLUG=""
if git_url=$(git remote get-url origin 2>/dev/null); then
  _u=${git_url%.git}; _repo=${_u##*/}; _rest=${_u%/*}
  REPO_SLUG="${_rest##*[:/]}/${_repo}"
fi
say "This repo has an upstream as well as a fork, so gh has to be told which one"
say "these secrets belong to."
say "Detected from 'origin': ${REPO_SLUG:-(none)}"
if ! confirm "Use that repository?"; then
  ask REPO_SLUG "Repository (owner/name):"
fi
export GH_REPO="$REPO_SLUG"
printf '\n'

gh_put_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN" || true
gh_put_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID" || true
printf '\n'

secrets_instructions() {
  step "Under Secrets and variables -> Actions -> Secrets, add or confirm:"
  copyable "CLOUDFLARE_API_TOKEN    = the token from stage 1"
  copyable "CLOUDFLARE_ACCOUNT_ID   = ${CLOUDFLARE_ACCOUNT_ID}"
}
gh_reads_secrets() { gh secret list >/dev/null 2>&1; }
gh_stage "both Cloudflare secrets" gh_reads_secrets check_secrets \
  secrets_instructions "https://github.com/${REPO_SLUG}/settings/secrets/actions"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Arm the workflow's live checks"
say "The 'Check the live site' step in release.yml runs only when the repository"
say "variable CLOUDFLARE_CHECKS holds the string 'true'. Everything it asserts is"
say "now in place, so turn it on and leave it on."
printf '\n'

gh_put_var CLOUDFLARE_CHECKS "true" || true
printf '\n'

var_instructions() {
  step "Under Secrets and variables -> Actions -> Variables, add:"
  copyable "CLOUDFLARE_CHECKS = true"
  note "The value is the literal string true, lower case."
}
gh_reads_vars() { gh variable list >/dev/null 2>&1; }
gh_stage "CLOUDFLARE_CHECKS=true" gh_reads_vars check_var \
  var_instructions "https://github.com/${REPO_SLUG}/settings/variables/actions"

finish
note "Next: the first deploy. Run the Release workflow with workflow_dispatch on"
note "the latest tag's ref and cloudflare_web checked, then watch the size guard"
note "and the live checks pass."
note "  https://github.com/${REPO_SLUG}/actions/workflows/release.yml"
printf '\n'
